# Used to add feature flags in the app to control access to certain features.
features:
  detailed_guidance_enabled: false

forms_api:
  # Authentication key to authenticate forms-runner to forms-api
  auth_key: changeme
  # URL to form-api endpoints
  base_url: http://localhost:9292

forms_runner:
  # Base URL to point users to the app in the UI
  url: http://localhost:3001

# Settings for GOV.UK Notify api & email templates
govuk_notify:
  api_key: changeme
  submission_email_confirmation_code_email_template_id: ce2638ab-754c-416d-8df6-c0ccb5e1a688

# When set to true, any capybara tests will run chrome normally rather than in headless mode.
show_browser_during_tests: false

maintenance_mode:
  # When set to true, All pages will render 'Maintenance mode' message
  enabled: false
  # List of IP addresses which will bypass the maintenance mode message as a comma seperated string, optionally using CIDR notation eq. "127.0.0.1, 192.192.192.192/32, 0.0.0.0/24"
  bypass_ips:

# Configuration for Sentry
# Sentry will only initialise if dsn is set to some other value
sentry:
  dsn:
  environment: local

# How we authenticate users
auth_provider: # use default auth_provider from environment

auth0:
  client_id: changeme
  client_secret:
  domain: changeme.uk.auth0.com

basic_auth:
  username: basic_auth_user
  password:
  organisation:
    name: GDS User Research
    slug: gds-user-research
    govuk_content_id: "00000000-0000-0000-0000-000000000000"

# CDDO SSO at sso.service.security.gov.uk via OpenID Connect
cddo_sso:
  identifier: changeme
  secret:

forms_env: local
